# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pactflow
email: hello@pactflow.io
description: >
  Pactflow is the leading contract-testing collaboration tool.
  We make it easy to test and deploy microservices, serverless
  functions and APIs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pactflow.io" # the base hostname & protocol for your site
destination: public # random hash for security purposes

collections:
  page:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_page"
      type: "pages"
    values:
      layout: page
      output: true


# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
exclude:
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Readme.md"
  - vendor
