---
env:
  AWS_REGION: ap-southeast-2
  AWS_DEFAULT_REGION: ap-southeast-2

steps:
  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Deploy staging.pactflow.io'
    env:
      JEKYLL_ENV: dev
      ENVIRONMENT: dev
    agents:
      queue: pact-dev

  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Deploy staging.pactflow.io'
    env:
      JEKYLL_ENV: dev
      ENVIRONMENT: dev
    agents:
      queue: pact

  - block: ":rocket: Release!"

  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Production Deploy - pactflow.io'
    env:
      JEKYLL_ENV: prod
      ENVIRONMENT: prod
    agents:
      queue: pact-dev

  - wait

  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Production Deploy - pactflow.io'
    env:
      JEKYLL_ENV: prod
      ENVIRONMENT: prod
    agents:
      queue: pact

