---
env:
  AWS_REGION: ap-southeast-2
  AWS_DEFAULT_REGION: ap-southeast-2

steps:
  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Deploy staging.pactflow.io'
    env:
      JEKYLL_ENV: dev
      ENVIRONMENT: dev
      S3BUCKET_NAME: staging.pactflow.io
      HOST_NAME: staging.pactflow.io
    agents:
      queue: pact-dev

  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Deploy staging-www.pactflow.io'
    env:
      JEKYLL_ENV: dev
      ENVIRONMENT: dev
      S3BUCKET_NAME: www.staging.pactflow.io
      HOST_NAME: staging.pactflow.io
    agents:
      queue: pact-prod

  - block: ":rocket: Release!"

  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Production Deploy - pactflow.io'
    env:
      JEKYLL_ENV: prod
      ENVIRONMENT: prod
      S3BUCKET_NAME: pactflow.io
      HOST_NAME: pactflow.io
    agents:
      queue: pact-dev

  - wait

  - command: |-
      ./shell/bundle.sh
      ./shell/deploy.sh
    label: ':rocket: Production Deploy - www.pactflow.io'
    env:
      JEKYLL_ENV: prod
      ENVIRONMENT: prod
      S3BUCKET_NAME: www.pactflow.io
      HOST_NAME: pactflow.io
    agents:
      queue: pact-prod

