AWSTemplateFormatVersion: "2010-09-09"
Description: >

  Pactflow website certificate
  This template must be deployed in us-east-1 due to ACM integration
  with CloudFront

Parameters:
  HostedZone:
    Description: HostedZone to attach the domain to
    Type: String
    Default: Z2KANQBPTUQA1W #pactflow.io
  HostedZoneName:
    Description: HostedZone to attach the domain to
    Type: String
    Default: pactflow.io
  HostName:
    Description: Domain name to host the website on
    Type: String
  Environment:
    Description: One of 'dev' or 'prod'
    AllowedPattern: '[A-Za-z][A-Za-z0-9\-]*'
    Type: String
    Default: dev

Resources:
    WebsiteBucket:
        Type: AWS::S3::Bucket
        Properties:
           AccessControl: PublicRead
           BucketName: !Sub ${Environment}-pactflow-website
          #  BucketName: !Ref Hostname # TODO: re-enable this
           WebsiteConfiguration:
              ErrorDocument: 404.html
              IndexDocument: index.html

    WebsiteCertificate:
        Type: AWS::CertificateManager::Certificate
        Properties:
            DomainName: !Ref HostName
            ValidationMethod: DNS
            SubjectAlternativeNames:
              - !Sub "www.${HostName}"

    WebsiteDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - Id: only-origin
                      DomainName: !Sub "${HostName}.s3-website-${AWS::Region}.amazonaws.com"
                      CustomOriginConfig:
                        HTTPPort: '80'
                        HTTPSPort: '443'
                        OriginProtocolPolicy: http-only
                Enabled: 'true'
                DefaultCacheBehavior:
                    ForwardedValues:
                        QueryString: 'true'
                    TargetOriginId: only-origin
                    ViewerProtocolPolicy: redirect-to-https
                DefaultRootObject: index.html
                Aliases:
                    - !Ref HostName
                    - !Sub "www.${HostName}"
                ViewerCertificate:
                    AcmCertificateArn: !Ref WebsiteCertificate
                    SslSupportMethod: sni-only

    WebsiteDNSRecord:
      Type: AWS::Route53::RecordSet
      Properties:
          HostedZoneName: !Ref 'HostedZoneName'
          Comment: DNS name for my instance.
          Name: staging.pactflow.io
          Type: A
          TTL: '500'
          ResourceRecords:
          - !GetAtt WebsiteDistribution.DomainName
          - !Sub 'www.${WebsiteDistribution.DomainName}'

Outputs:
  CertificateArn:
    Description: Arn of the certificate in us-east-1
    Value: !Ref WebsiteCertificate